import Image from "next/image";
import Link from "next/link";
import { InstagramSection } from "@/components/instagram/InstagramSection";
import { ReservationCTA, SectionHeading } from "@/components/UI";
import { concerns, faqs, gallery, treatments } from "@/data/site";
import { recruitData } from "@/data/recruit";
import { siteConfig } from "@/config/site";

export default function Home() { return <>
  <section className="home-hero"><Image src="/images/yasashisa/clinic-hero-generated.webp" alt="青と白を基調とした明るく清潔な院内" fill priority sizes="100vw" /><div className="hero-shade" /><div className="container hero-content"><p className="eyebrow light">YASASHISA SEIKOTSUIN</p><h1><span className="phrase">身体の悩みに、</span><span className="phrase">やさしく向き合う。</span></h1><p>丁寧に聞く。状態を見極める。無理のない施術で、毎日を動きやすく。</p><div className="hero-actions"><a className="button" href={siteConfig.reservationUrl} target="_blank" rel="noopener noreferrer">Web予約する ↗</a><Link className="button button-glass" href="/first">初めての方へ</Link></div><ul><li>東中神駅南口 徒歩4分</li><li>駐車場5台</li><li>土日も20時まで</li></ul></div></section>
  <section className="section concerns"><div className="container split"><SectionHeading eyebrow="CONCERNS" title="こんなお悩みはありませんか？" lead="痛む場所だけにとらわれず、生活習慣や身体の使い方まで丁寧に確認します。" /><div className="concern-list">{concerns.map((item, i) => <div key={item}><span>{String(i + 1).padStart(2, "0")}</span><strong>{item}</strong></div>)}</div></div></section>
  <section className="section pale"><div className="container"><SectionHeading eyebrow="OUR APPROACH" title="一人ひとりに合った施術を" lead="同じように見える不調でも、原因や生活背景は人それぞれ。分かりやすい説明と、無理のない施術を大切にしています。" align="center" /><div className="feature-grid"><article><b>01</b><h3>丁寧にお話を伺う</h3><p>不調の経緯や日常の過ごし方まで、焦らずお聞きします。</p></article><article><b>02</b><h3>状態を分かりやすく説明</h3><p>身体の状態と施術の考え方を、納得できる言葉でお伝えします。</p></article><article><b>03</b><h3>続けやすい環境</h3><p>駅徒歩4分、駐車場5台。明るく広い院内でお迎えします。</p></article></div></div></section>
  <section className="section"><div className="container"><SectionHeading eyebrow="TREATMENT" title="施術・メニュー" lead="お悩みや身体の状態に合わせて、必要な施術をご提案します。" /><div className="treatment-grid">{treatments.map((item) => <article key={item.title}><div className="card-image"><Image src={item.image} alt={`${item.title}の施術イメージ`} fill sizes="(max-width: 700px) 100vw, 33vw" /></div><h3>{item.title}</h3><p>{item.text}</p></article>)}</div><Link className="text-link section-link" href="/treatment">施術・メニューを詳しく見る →</Link></div></section>
  <section className="section gallery-preview"><div className="container"><SectionHeading eyebrow="CLINIC GALLERY" title="明るく、清潔で、安心できる院内" lead="施術ベッド10台を備えた広い空間と、カーテンで仕切れる施術スペースをご用意しています。" /><div className="gallery-strip">{gallery.slice(0, 4).map((item, i) => <Image key={item.src} className={i === 0 ? "wide" : ""} src={item.src} alt={item.alt} width={700} height={520} />)}</div><Link className="text-link section-link" href="/gallery">院内紹介を見る →</Link></div></section>
  <InstagramSection />
  <section className="section access-home"><div className="container access-grid"><div><SectionHeading eyebrow="ACCESS" title="東中神駅南口から徒歩4分" lead="駅から近く、院の斜向かいには5台分の駐車場もあります。お仕事帰りやお子さま連れでも通いやすい環境です。" /><address>{siteConfig.address}</address><div className="stacked-text"><p>9:00〜12:30／15:00〜20:00</p><p>年末年始を除き営業</p></div><div className="inline-actions"><Link className="button" href="/access">アクセス詳細</Link><a className="button button-outline" href={siteConfig.mapUrl} target="_blank" rel="noopener noreferrer">Googleマップ ↗</a></div></div><Image src="/images/yasashisa/clinic-original.jpg" alt="やさしさ 昭島東中神整骨院の院内" width={720} height={540} /></div></section>
  <section className="section pale"><div className="container"><SectionHeading eyebrow="FAQ" title="よくある質問" /><div className="faq-list">{faqs.slice(0, 3).map((item) => <details key={item.q}><summary>{item.q}</summary><p>{item.a}</p></details>)}</div><Link className="text-link section-link" href="/faq">よくある質問をもっと見る →</Link></div></section>
  <section className="section recruit-home"><div className="container recruit-panel"><div><p className="eyebrow light">RECRUIT</p><h2>一緒に働く仲間を募集しています</h2><p className="recruit-copy">好きで溢れる世界を、仲間とつくる。</p><p>株式会社フチでは、経験や年齢だけではなく「この人と一緒に働きたいと思えるか」を大切にしています。</p></div><div><ul>{recruitData.highlights.map((item) => <li key={item}>{item}</li>)}</ul><Link className="button button-white" href="/recruit">採用情報を見る</Link></div></div></section>
  <ReservationCTA />
  </>; }
